Repository chebur/pjsip, pull requests merged in 2019-08, with the labels that each got.

#78 Moved issue template as we only have a single template.
  .github/ISSUE_TEMPLATE.md
Labels: Type: Maintenance

#80 Update main.yml
  .github/workflows/main.yml
Labels: Status: Accepted, Type: Maintenance

#81 Added stale action to close stale PRs and issues.
  .github/workflows/stale.yml
Labels: Status: Review Needed, Type: Maintenance
